jwt:
  # 86400000 : 24시간
  access-token-expired-time: 86400000
  refresh-token-expired-time: 8640000000
  secret-key: GLUCOCARE-SERVER-SECURITY-SECRET-KEY
cgm:
  api-secret: 6657e0a81db2984bcc01291d854c9af3be759471
spring:
  application:
    name: server
  datasource:
    url: jdbc:mysql://localhost:3306/glucocare?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: glucocare
    password: glucocare0116
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org:
      springframework: INFO
